"""update db models

Revision ID: 77eb2288c622
Revises: 0b1f318ba8ae
Create Date: 2022-11-02 11:21:32.902564

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '77eb2288c622'
down_revision = '0b1f318ba8ae'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Cards', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('Cards', 'version',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('Cards', 'new_in_hand_action',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('Cards', 'rotation_condition',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('Cards', 'normal_desc',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('Cards', 'rotate_desc',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('Cards', 'icon',
               existing_type=postgresql.BYTEA(),
               nullable=False)
    op.alter_column('Deck', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('Deck', 'version',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('Games', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('Games', 'save_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('Games', 'state',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('Rules', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('Rules', 'version',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('Rules', 'rules',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('User', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('User', 'mail',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('User', 'passwd',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('User', 'logedin',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('User', 'logedin',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('User', 'passwd',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('User', 'mail',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('User', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('Rules', 'rules',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('Rules', 'version',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('Rules', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('Games', 'state',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('Games', 'save_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('Games', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('Deck', 'version',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('Deck', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('Cards', 'icon',
               existing_type=postgresql.BYTEA(),
               nullable=True)
    op.alter_column('Cards', 'rotate_desc',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('Cards', 'normal_desc',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('Cards', 'rotation_condition',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('Cards', 'new_in_hand_action',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('Cards', 'version',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('Cards', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
